# Generated by Django 4.2.4 on 2023-09-01 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ElectronicSynopsis', '0002_section_item_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.IntegerField()),
            ],
        ),
    ]
