# Generated by Django 4.2.4 on 2023-09-11 03:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ElectronicSynopsis', '0004_customuser_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attach_id', models.IntegerField(default=-1)),
                ('name', models.CharField(blank=True, max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
