# Generated by Django 4.2.4 on 2023-09-11 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ElectronicSynopsis', '0005_usericon'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='usericon',
            index=models.Index(fields=['user'], name='ElectronicS_user_id_f6a6e3_idx'),
        ),
    ]
