# Generated by Django 4.2.4 on 2023-09-11 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ElectronicSynopsis', '0006_usericon_electronics_user_id_f6a6e3_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='usericon',
            name='ElectronicS_user_id_f6a6e3_idx',
        ),
        migrations.AddIndex(
            model_name='usericon',
            index=models.Index(fields=['user', 'attach_id'], name='ElectronicS_user_id_ddfd58_idx'),
        ),
    ]
