# Generated by Django 4.2.4 on 2023-09-14 07:11

import ElectronicSynopsis.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ElectronicSynopsis', '0007_remove_usericon_electronics_user_id_f6a6e3_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'светлая'), ('dark', 'темная')], default='light', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, ElectronicSynopsis.models.JsonBuilder),
        ),
    ]
