# Generated by Django 4.2.4 on 2023-09-30 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ElectronicSynopsis', '0009_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='keys',
            name='response_key',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
    ]
