# Generated by Django 4.2.4 on 2023-09-30 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ElectronicSynopsis', '0010_keys_response_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keys',
            name='response_key',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
