# Generated by Django 4.2.4 on 2023-10-02 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ElectronicSynopsis', '0011_alter_keys_response_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keys',
            name='private_key',
        ),
        migrations.RemoveField(
            model_name='keys',
            name='public_key',
        ),
        migrations.RemoveField(
            model_name='keys',
            name='response_key',
        ),
        migrations.RemoveField(
            model_name='keys',
            name='user',
        ),
        migrations.AddField(
            model_name='keys',
            name='client_public_key',
            field=models.TextField(blank=True, max_length=2048),
        ),
        migrations.AddField(
            model_name='keys',
            name='expire',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='keys',
            name='server_private_key',
            field=models.TextField(default='', max_length=2048),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='keys',
            name='server_public_key',
            field=models.TextField(default='', max_length=2048),
            preserve_default=False,
        ),
    ]
