# Generated by Django 4.2.4 on 2023-10-04 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ElectronicSynopsis', '0012_remove_keys_private_key_remove_keys_public_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='keys',
            name='hash',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
