upstream backend_proxy {
    server "mi_app:8000";
}

upstream frontend {
    server "mi-frontend";
}

server {
    # виртуальный сервер. Проксирование по доменным именам
    listen       80 default_server;
    listen       [::]:80 default_server;
    server_name  _; # Обслуживает любой хост

    location @backend {
        # реверс-проксирование, по какому адресу отправлять запросы 
        proxy_pass http://backend_proxy;
    }

    location ~ ^/(admin) {
        proxy_pass http://backend_proxy;
        try_files $uri $uri/ @backend;  # try_files ограничивает доступ в закрытую секцию файловой системы
    }

    # location для обработки статики Django
    location /static/admin/ {
        proxy_pass http://backend_proxy;
    }

    location /static/images/ {
        proxy_pass http://backend_proxy;
    }

    location /static/avatars_items/ {
        proxy_pass http://backend_proxy;
    }

    location /static/avatars_sections/ {
        proxy_pass http://backend_proxy;
    }

     location /static/avatars_users/ {
        proxy_pass http://backend_proxy;
    }


    location ~ ^/api/v1/ {
        proxy_pass http://backend_proxy;
    }

    # Frontend (React)
    location / {
        proxy_pass http://frontend;
    }

    location /static/ {
        proxy_pass http://frontend;
    }


    error_page   404              /404.html;

    # redirect server error pages to the static page /50x.html
    #
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   html;
    }
} 